In [3]:
import pandas as pd
data=pd.read_csv('/content/drive/MyDrive/Datahack/testdata.csv')
data.head()

,Unnamed: 0,order_id,item_name,quantity
0,0,ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3...,Cosmonaut,1
1,1,ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3...,Krombacher,1
2,2,ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3...,Ahi Tuna,1
3,3,ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3...,Little Gem Salad,1
4,4,ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3...,Fire Pie,1

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 665847 entries, 0 to 665846
Data columns (total 4 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  665847 non-null  int64
 1   order_id    665847 non-null  object
 2   item_name   665847 non-null  object
 3   quantity    665847 non-null  int64
dtypes: int64(2), object(2)
memory usage: 20.3+ MB

In [5]:
df=data.drop(['Unnamed: 0'],axis=1)
df.head()

,order_id,item_name,quantity
0,ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3...,Cosmonaut,1
1,ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3...,Krombacher,1
2,ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3...,Ahi Tuna,1
3,ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3...,Little Gem Salad,1
4,ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3...,Fire Pie,1

In [6]:
df[df['item_name']=="Focaccia, Spicy Meatballs"]

Empty DataFrame
Columns: [order_id, item_name, quantity]
Index: []

In [7]:
df=df.groupby(['order_id','item_name'])['quantity'].sum().unstack().reset_index().fillna(0).set_index('order_id')
df.head()

item_name,Coffeee Cake,$10 N/A Bev Package,$10 Upcharge,$15 Upcharge,$2 Oysters,$2 Upcharge,$20 Kids Brunch,$25 Plated,$25 Upcharge,$3 Centennario Shot,...,how i like my coffee,lambrusco risotto,marinated olives,pappardelle,pig picnic pita,rack of lamb,smash burger,summer peppers,sunset on damen,whole dover sole
order_id,,,,,,,,,,,,,,,,,,,,,
ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3BfUmVzZXJ2YXRpb25BY3R1YWwY---TiRsM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3BfUmVzZXJ2YXRpb25BY3R1YWwY---jqRsM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3BfUmVzZXJ2YXRpb25BY3R1YWwY--6CghsM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3BfUmVzZXJ2YXRpb25BY3R1YWwY--6L6BoM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3BfUmVzZXJ2YXRpb25BY3R1YWwY--6_4h4M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
def encode_quantity(x):
    if x<=0:
        return 0
    if x>0:
        return 1
df=df.applymap(encode_quantity)
df.head()

item_name,Coffeee Cake,$10 N/A Bev Package,$10 Upcharge,$15 Upcharge,$2 Oysters,$2 Upcharge,$20 Kids Brunch,$25 Plated,$25 Upcharge,$3 Centennario Shot,...,how i like my coffee,lambrusco risotto,marinated olives,pappardelle,pig picnic pita,rack of lamb,smash burger,summer peppers,sunset on damen,whole dover sole
order_id,,,,,,,,,,,,,,,,,,,,,
ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3BfUmVzZXJ2YXRpb25BY3R1YWwY---TiRsM,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3BfUmVzZXJ2YXRpb25BY3R1YWwY---jqRsM,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3BfUmVzZXJ2YXRpb25BY3R1YWwY--6CghsM,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3BfUmVzZXJ2YXRpb25BY3R1YWwY--6L6BoM,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3BfUmVzZXJ2YXRpb25BY3R1YWwY--6_4h4M,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
df.describe()

item_name,Coffeee Cake,$10 N/A Bev Package,$10 Upcharge,$15 Upcharge,$2 Oysters,$2 Upcharge,$20 Kids Brunch,$25 Plated,$25 Upcharge,$3 Centennario Shot,...,how i like my coffee,lambrusco risotto,marinated olives,pappardelle,pig picnic pita,rack of lamb,smash burger,summer peppers,sunset on damen,whole dover sole
count,80517.000000,80517.000000,80517.000000,80517.000000,80517.000000,80517.000000,80517.000000,80517.000000,80517.000000,80517.000000,...,80517.000000,80517.000000,80517.000000,80517.000000,80517.000000,80517.000000,80517.000000,80517.000000,80517.000000,80517.000000
mean,0.000782,0.000012,0.000037,0.000286,0.000224,0.000012,0.000012,0.000012,0.000012,0.000012,...,0.000447,0.000310,0.002447,0.017437,0.023759,0.000149,0.001751,0.005105,0.056448,0.000025
std,0.027961,0.003524,0.006104,0.016899,0.014950,0.003524,0.003524,0.003524,0.003524,0.003524,...,0.021140,0.017618,0.049404,0.130895,0.152298,0.012207,0.041811,0.071264,0.230786,0.004984
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [10]:
# df["Focaccia, Spicy Meatballs"].value_counts()

#Filtering dataset with items greater than 1

In [11]:
df_filter=df[(df>0).sum(axis=1)>=2]
df_filter

item_name,Coffeee Cake,$10 N/A Bev Package,$10 Upcharge,$15 Upcharge,$2 Oysters,$2 Upcharge,$20 Kids Brunch,$25 Plated,$25 Upcharge,$3 Centennario Shot,...,how i like my coffee,lambrusco risotto,marinated olives,pappardelle,pig picnic pita,rack of lamb,smash burger,summer peppers,sunset on damen,whole dover sole
order_id,,,,,,,,,,,,,,,,,,,,,
ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3BfUmVzZXJ2YXRpb25BY3R1YWwY---TiRsM,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3BfUmVzZXJ2YXRpb25BY3R1YWwY---jqRsM,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3BfUmVzZXJ2YXRpb25BY3R1YWwY--6CghsM,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3BfUmVzZXJ2YXRpb25BY3R1YWwY--6L6BoM,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3BfUmVzZXJ2YXRpb25BY3R1YWwY--6_4h4M,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ahNzfnNldmVucm9vbXMtc2VjdXJlcigLEhtuaWdodGxvb3BfUmVzZXJ2YXRpb25BY3R1YWwYgIDszuPA1AsM,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ahNzfnNldmVucm9vbXMtc2VjdXJlcigLEhtuaWdodGxvb3BfUmVzZXJ2YXRpb25BY3R1YWwYgIDszuPY7QkM,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ahNzfnNldmVucm9vbXMtc2VjdXJlcigLEhtuaWdodGxvb3BfUmVzZXJ2YXRpb25BY3R1YWwYgIDszubI0wgM,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ahNzfnNldmVucm9vbXMtc2VjdXJlcigLEhtuaWdodGxvb3BfUmVzZXJ2YXRpb25BY3R1YWwYgIDszv2iywoM,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ahNzfnNldmVucm9vbXMtc2VjdXJlcigLEhtuaWdodGxvb3BfUmVzZXJ2YXRpb25BY3R1YWwYgIDszvC57AgM,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

#Applying the apriori algorithm

In [12]:
from mlxtend.frequent_patterns import apriori

frequent_items=apriori(df_filter,min_support=0.03,use_colnames=True).sort_values('support',ascending=False).reset_index(drop=True)
frequent_items['length']=frequent_items['itemsets'].apply(lambda x:len(x))
frequent_items

     support                                itemsets  length
0   0.394044                              (Focaccia)       1
1   0.200457                       (Bubbling Shrimp)       1
2   0.178284                 (Bucatini Cacio e Pepe)       1
3   0.168103                       (Spicy Meatballs)       1
4   0.142145              (The "etta" Chopped Salad)       1
..       ...                                     ...     ...
88  0.031929                           (Orecchiette)       1
89  0.031742  (Ricotta Pillows, Cavatelli Bolognese)       2
90  0.031679  (Bucatini Cacio e Pepe, Wild Mushroom)       2
91  0.031480     (Little Gem Salad, Spicy Meatballs)       2
92  0.031192                                (Aperol)       1

[93 rows x 3 columns]

In [13]:
from mlxtend.frequent_patterns import association_rules

df=association_rules(frequent_items,metric='lift',
                  min_threshold=1).sort_values('lift',ascending=False).reset_index(drop=True)

In [14]:
df

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,"(Focaccia, Spicy Meatballs)",(Bucatini Cacio e Pepe),0.076475,0.178284,0.032179,0.420778,2.360152,0.018545,1.418653
1,(Bucatini Cacio e Pepe),"(Focaccia, Spicy Meatballs)",0.178284,0.076475,0.032179,0.180493,2.360152,0.018545,1.126928
2,(Bucatini Cacio e Pepe),(Ricotta Pillows),0.178284,0.125131,0.051229,0.287346,2.296357,0.028920,1.227620
3,(Ricotta Pillows),(Bucatini Cacio e Pepe),0.125131,0.178284,0.051229,0.409404,2.296357,0.028920,1.391333
4,(Cavatelli Bolognese),(Ricotta Pillows),0.119522,0.125131,0.031742,0.265573,2.122355,0.016786,1.191226
...,...,...,...,...,...,...,...,...,...
77,(Focaccia),(Caesar),0.394044,0.093052,0.040199,0.102016,1.096336,0.003532,1.009983
78,(Bubbling Shrimp),(Focaccia),0.200457,0.394044,0.083721,0.417648,1.059903,0.004732,1.040533
79,(Focaccia),(Bubbling Shrimp),0.394044,0.200457,0.083721,0.212465,1.059903,0.004732,1.015247
80,(Rack Roasted Oysters),(Focaccia),0.086906,0.394044,0.036164,0.416128,1.056044,0.001919,1.037823
81,(Focaccia),(Rack Roasted Oysters),0.394044,0.086906,0.036164,0.091777,1.056044,0.001919,1.005363

In [15]:
df.to_csv("Apriori_Dataset.csv")